playSoftMIDI: playSoftMIDI.c
	gcc playSoftMIDI.c -o playSoftMIDI -framework CoreAudio -framework CoreMidi\
            -framework AudioToolbox -framework CoreServices -framework AudioUnit

clean:
	rm -rf playSoftMIDI
